spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        test-in:
          destination: test
          contentType: application/json
        test-out:
          destination: test
          contentType: application/json